# Generated by Django 5.0.4 on 2024-07-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255, null=True)),
                ('firstname', models.CharField(max_length=255, null=True)),
                ('middlename', models.CharField(max_length=255, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('place_of_birth', models.CharField(max_length=255, null=True)),
                ('sex', models.CharField(max_length=255, null=True)),
                ('civil_status', models.CharField(max_length=255, null=True)),
                ('height', models.CharField(max_length=255, null=True)),
                ('weight', models.CharField(max_length=255, null=True)),
                ('blood_type', models.CharField(max_length=255, null=True)),
                ('gsis', models.CharField(blank=True, max_length=255, null=True)),
                ('pagibig', models.CharField(blank=True, max_length=255, null=True)),
                ('philhealth', models.CharField(blank=True, max_length=255, null=True)),
                ('sss', models.CharField(blank=True, max_length=255, null=True)),
                ('tin', models.CharField(blank=True, max_length=255, null=True)),
                ('agency_employee', models.CharField(blank=True, max_length=255, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=255, null=True)),
                ('residential_address', models.CharField(max_length=255, null=True)),
                ('residential_zipcode', models.CharField(max_length=255, null=True)),
                ('permanent_address', models.CharField(max_length=255, null=True)),
                ('permanent_zipcode', models.CharField(max_length=255, null=True)),
                ('telephone', models.CharField(max_length=255, null=True)),
                ('mobile', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
